export const ContactListTypes = {
  FETCH_CONTACT_LIST_REQUEST: 'FETCH_CONTACT_LIST_REQUEST',
  FETCH_CONTACT_LIST_SUCCESS: 'FETCH_CONTACT_LIST_SUCCESS',
  FETCH_CONTACT_LIST_FAILURE: 'FETCH_CONTACT_LIST_FAILURE',
};
